# Generated by Django 4.1.12 on 2023-11-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_livro', models.ImageField(upload_to='img_livro/', verbose_name='imagem do livro')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('local', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('quantidade_exemplares', models.IntegerField(verbose_name='Livros disponíveis')),
                ('classificacao', models.IntegerField(verbose_name='classificação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.categoria')),
            ],
        ),
    ]
