# Generated by Django 4.1.12 on 2023-12-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_pratileira'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='sob_demanda',
            field=models.BooleanField(default=False),
        ),
    ]
